# Generated by Django 4.2.2 on 2023-06-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_preco'),
        ('colaboradores', '0002_alter_colaborador_cpf_alter_colaborador_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='produtos',
            field=models.ManyToManyField(to='produtos.produto'),
        ),
    ]
