# Generated by Django 4.2.2 on 2023-06-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_colaborador_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='produtos',
        ),
    ]
