# Generated by Django 4.2.3 on 2023-07-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
