# Generated by Django 4.2.3 on 2023-07-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_estoquesaida_estoqueentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquesaida',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='estoquesaida',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='EstoqueEntrada',
        ),
        migrations.DeleteModel(
            name='EstoqueSaida',
        ),
    ]
