# Generated by Django 4.2.3 on 2023-07-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_estoquemovimentacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstoqueMovimentacao',
        ),
    ]
