# Generated by Django 4.2.3 on 2023-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('ingresso', 'Ingresso'), ('roupa', 'Roupa')], default='normal', max_length=8),
        ),
    ]
