# Generated by Django 4.2.3 on 2023-07-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('alcoolico', 'Alcoólico'), ('ingresso', 'Ingresso'), ('vestimenta', 'Vestimenta')], default='normal', max_length=10),
        ),
    ]
