# Generated by Django 4.2.2 on 2023-06-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compraproduto_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
