# Generated by Django 4.2.2 on 2023-06-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproduto',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='compraproduto',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='CompraProduto',
        ),
    ]
