# Generated by Django 4.2.2 on 2023-06-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compraproduto_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproduto',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_produtos', to='compras.compra'),
        ),
    ]
