# Generated by Django 4.2.2 on 2023-06-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompraProduto',
        ),
    ]
