# Generated by Django 4.2.2 on 2023-06-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_preco'),
        ('compras', '0004_delete_compraproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='compras.CompraProduto', to='produtos.produto'),
        ),
    ]
