# Generated by Django 4.2.2 on 2023-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='login',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
