# Generated by Django 4.2.2 on 2023-06-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_preco'),
        ('colaboradores', '0004_remove_colaborador_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='produtos',
            field=models.ManyToManyField(related_name='Compra', to='produtos.produto'),
        ),
    ]
