# Generated by Django 4.2.2 on 2023-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0006_remove_colaborador_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
