# Generated by Django 4.2.2 on 2023-06-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0007_alter_colaborador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
