# Generated by Django 4.2.3 on 2023-07-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0008_alter_colaborador_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(default='teste@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
