# Generated by Django 4.2.3 on 2023-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0009_colaborador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
